language: php

php:
  - 5.5

install:
  - travis_retry composer install

before_script:
  - "mysql -e 'create database `timefragment`;'"
  - php artisan migrate -n
  - php artisan dump-autoload

script: phpunit ./app/tests/ExampleTest.php