language: php

php:
  - 5.5

install:
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - "mysql -e 'create database `pinai`;'"
  - composer install -n --prefer-source
  - php artisan migrate -n
  - php artisan dump-autoload

script: phpunit ./app/tests/ExampleTest.php